language: java

env:
  global:
    - CODECOV_TOKEN=6dbac3f4-72e1-43c3-a6b1-2a1354229316
    - CODACY_PROJECT_TOKEN=fa27a35fba494219a668509c260daec1
jdk:
  - openjdk11
script:
  - ./mvnw clean install

notifications:
  email: rakesh8693@gmail.com 
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report